### ISSUE TITLE
Document goals and limitations of this repo

### ISSUE THREAD

**Issue by hebasto** [bitcoin-core/gui-qml#1]
It should be clear for new contributors what are goals of this repo, and what are its limitations.

Some limitations are obvious -- as QML module is not a part of depends for now, only builds with system packages are available.

Also, as this repo is experimental, it seems reasonable to limit systems on which code is tested. My suggestion is:
- latest Ubuntu LTS
- latest Ubuntu
- latest macOS

As for goals, I reiterate [my suggestion](https://github.com/bitcoin-core/gui/issues/352) to adopt the [Bitcoin Design Guide](https://bitcoin.design/guide/) and follow it.

**Comment by michaelfolkson** [comment]
Discussion of QML in this issue for adding historical context: https://github.com/bitcoin/bitcoin/pull/16883

**Comment by GBKS** [comment]
Just wanted to share my thoughts on goals. I think it would be fantastic if this repo would not attempt to directly re-create the QT widgets GUI just using a different technical framework. This clean slate could be a great opportunity to build on what has worked well, and improve or rethink what hasn't worked well. It's very rare to get such an opportunity. This could end up in a really big discussion with lots of personal preference, so not sure if this issue is the right place for it.

If I understand correctly, building out an interface in QML is a lot more work than using widgets, as the UI elements and layouts have to be mostly custom coded. To simplify this work, it could be helpful to design and implement an application style guide with standard components, like the ones [here in the wallet UI kit](https://www.figma.com/file/VB3GQdAnhl8yta44DY3PSV/Bitcoin-Wallet-UI-Kit?node-id=1%3A3). With such a foundation, it becomes much easier to lay out actual screens as the individual pieces are already done and "just" need to be laid out and hooked up to data and events. A developer I worked with on another QML project ended up creating a second application for development that only included the UI code. This second application built much faster and sped up the UI work. For web applications, tools like [Storybook](https://storybook.js.org) exist, maybe it could serve as inspiration. Overall, I think there's a lot of benefit in getting this development workflow right. Maybe having a great UI development workflow could be a goal?

**Comment by promag** [comment]
> I think it would be fantastic if this repo would not attempt to directly re-create the QT widgets GUI just using a different technical framework.

👍 

> as the UI elements and layouts have to be mostly custom coded

I'd base on https://doc.qt.io/qt-5/qtquickcontrols-index.html where customization/styling is possible.

> A developer I worked with on another QML project ended up creating a second application for development that only included the UI code

LGTM.

**Comment by Bosch-0** [comment]
> I think it would be fantastic if this repo would not attempt to directly re-create the QT widgets GUI just using a different technical framework.

Yep, completely agree.

> To simplify this work, it could be helpful to design and implement an application style guide with standard components, like the ones here in the wallet UI kit.

Agree, getting a style guide established prior to any serious dev work on QML would be the best approach. This wasn't very feasible with widgets which inherited a lot of styling from the host OS making it much harder to create consistent designs.

We should ensure any further design efforts put towards the Qt Widgets GUI are portable to QML so that we are not regressing long term. https://github.com/bitcoin-core/gui/issues/314 is a good example of this as we can use those icons in both applications. I've discussed this with @jarolrod and there is still value in improving the widgets design through incremental patches / style sheets though any major UI changes should be focused on QML mockups (once a style guide is established that is).  

Here is some rough general steps (in order) we could take: 

1. Designers establish a style guide that lays out standard components - things like buttons, grids, fonts etc. 
2. Devs can begin building out these components in isolation from the application. 
3. Designers create a static QML GUI design using the style guide. This could start as soon as the style guide is finished. Having these designs out in the open may also be a good way to get entice developers to get on board. It could also sink a lot of time into something that never gets used so we should be careful in how we approach this. 
4. Devs begin building the QML GUI using the components built in step 2.

**Comment by Rspigler** [comment]
Very excited by this! Strong concept ACK

**Comment by hebasto** [comment]
@GBKS @Bosch-0 @promag 

Is [Exporting Designs from Figma](https://doc.qt.io/qtdesignstudio/figmaqtbridge.html) a thing?

**Comment by GBKS** [comment]
Overall, Figma has pretty good built-in tools for [exporting and inspecting designs](https://www.figma.com/best-practices/tips-on-developer-handoff/an-overview-of-figma-for-developers/). Those are all about getting design information out of Figma.

If I understand correctly, what the QT Figma bridge seems to do is to create direct links between a design file and code implementation and attempt to automate syncing between them. I've looked into tools like this before and believe they only work for very limited, highly static use cases. Could be worth investigating and maybe there are benefits, I just expect them to be limited.

If we used this, could the ownership of the linked design file be considered problematic? Figma files are tied to individual or team accounts (free up to 3 users). An ideal setup would allow for public collaboration like here on Github, but that's not possible at this moment, neither with Figma nor other design tools.
